MAP_LENGTH = screen.width * 0.7;
MAP_HEIGHT = screen.height * 0.9;
ASPECT_RATIO = MAP_HEIGHT / MAP_LENGTH
MAP_RESOLUTION = 100;

PIXEL_SIZE = MAP_LENGTH / MAP_RESOLUTION;

VEHICLE_SIZE = 8 
SENSOR_SIZE = 3
MOTOR_SIZE = SENSOR_SIZE

DEFAULT_VEHICLE3_STARTING_VELOCITY = 250

FPS = 60;
SECONDS_PATH_VISIBLE = 2