MAP_LENGTH = screen.width * 0.7;
MAP_HEIGHT = screen.height * 0.9;
ASPECT_RATIO = MAP_HEIGHT / MAP_LENGTH
MAP_RESOLUTION = 100;

PIXEL_SIZE = MAP_LENGTH / MAP_RESOLUTION;

VEHICLE_SIZE = 8 * PIXEL_SIZE
SENSOR_SIZE = 4 * PIXEL_SIZE

MOMENT_OF_INERTIA = 0.5 * Math.pow((VEHICLE_SIZE/2), 2)

FPS = 60;
SECONDS_PATH_VISIBLE = 2