// robot with a single sensor that moves faster the more intense the light is
class Robot1 {
    constructor(gyro, sensors, motorcontrollers, motors) {
        this.gyro = gyro;
        this.sensors = sensors;
        this.motorcontrollers = motorcontrollers;
        this.motors = motors;
    }

    move(dt) {
        this.gyro.vx = 0;
        this.gyro.vy = 0;

        for (i = 0; i < this.motors.length; i++) {
            let motor = this.motors[i];
            let fx = Math.cos(this.gyro.theta) * motor.getForce();
            let fy = Math.sin(this.gyro.theta) * motor.getForce();

            // let mass be 1 so that force = acceleration
            this.gyro.ax += fx;
            this.gyro.ay += fy;
        }
        this.gyro.vx += dt * this.gyro.ax;
        this.gyro.vy += dt * this.gyro.ay;

        this.gyro.x += dt * this.gyro.vx;
        this.gyro.y += dt * this.gyro.vy;
    }

    rotate(dt) {
        // find the torque generated by the motors
        // get the position of each motor
        // find the vector of the motor
        // find the torque of the motor
        
    }
}